version: '3.8'

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=realtor
    ports:
      - '5432:5432'
    restart: always
    networks:
      - app-network

  app:
    container_name: realtor-app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    restart: always
    networks:
      - app-network
    depends_on:
      - postgres

