POST http://localhost:3000/roles
Content-Type: application/json

{
    "name": "ADMIN"
}

###
GET http://localhost:3000/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjkzYzI1NC1mOTM5LTRlNTEtYmM0OC00MjU4ZTY0MDU4YzEiLCJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsInJvbGUiOiJkZDIxYjU4YS01MWY3LTQxMWUtODE4Mi0zNDRkNmQwYmY2NjYiLCJpYXQiOjE2OTU0MTYxMTQsImV4cCI6MTY5NTQxOTcxNH0.lolEzUtJ_fOzvehdZeqLs5sJqWR3g9SUwc3ECi0UMyY

###
GET http://localhost:3000/roles/5ccc66fe-f9cd-4039-9cad-f6738e3be061
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjkzYzI1NC1mOTM5LTRlNTEtYmM0OC00MjU4ZTY0MDU4YzEiLCJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsInJvbGUiOiJkZDIxYjU4YS01MWY3LTQxMWUtODE4Mi0zNDRkNmQwYmY2NjYiLCJpYXQiOjE2OTU0MTYxMTQsImV4cCI6MTY5NTQxOTcxNH0.lolEzUtJ_fOzvehdZeqLs5sJqWR3g9SUwc3ECi0UMyY

###
PATCH http://localhost:3000/roles/5ccc66fe-f9cd-4039-9cad-f6738e3be061
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjkzYzI1NC1mOTM5LTRlNTEtYmM0OC00MjU4ZTY0MDU4YzEiLCJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsInJvbGUiOiJkZDIxYjU4YS01MWY3LTQxMWUtODE4Mi0zNDRkNmQwYmY2NjYiLCJpYXQiOjE2OTU0MTYxMTQsImV4cCI6MTY5NTQxOTcxNH0.lolEzUtJ_fOzvehdZeqLs5sJqWR3g9SUwc3ECi0UMyY

{
    "name": "TESTE"
}
###
DELETE http://localhost:3000/roles/5ccc66fe-f9cd-4039-9cad-f6738e3be061
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNjkzYzI1NC1mOTM5LTRlNTEtYmM0OC00MjU4ZTY0MDU4YzEiLCJlbWFpbCI6ImFkbWluQGVtYWlsLmNvbSIsInJvbGUiOiJkZDIxYjU4YS01MWY3LTQxMWUtODE4Mi0zNDRkNmQwYmY2NjYiLCJpYXQiOjE2OTU0MTYxMTQsImV4cCI6MTY5NTQxOTcxNH0.lolEzUtJ_fOzvehdZeqLs5sJqWR3g9SUwc3ECi0UMyY
